#! /bin/sh
set -e
case "$1" in
	remove)
		dpkg-divert --package python-xml2rfc --remove --rename --divert /usr/bin/xml2rfc.tcl /usr/bin/xml2rfc
		;;

	purge|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
		;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 0
esac

